version: '3'
services:
  jsreport:
    container_name: jsreport_server
    image: 360f/oscar-jsreport:sat-latest
    ports:
      - 5488:5488
    environment:
      - DOCKER_ENABLE_CI=true
      - WEBSITES_ENABLE_APP_SERVICE_STORAGE=false