version: '3'

services:
  postgres:
    container_name: postgres_server
    image: postgres:12.13-alpine3.17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    #restart: always
    volumes:
      - D:\\projects\\docker-compose\\volumes\\postgres:/var/lib/postgresql/data
volumes:
  pg_data:
    driver: local