version: '3.5'

networks:
  storage:
    name: storage

volumes:
  data-elasticsearch:
  data-mongo:

services:
  # mongodb:
  #   image: mongo:${MONGODB_VERSION:-3.6}
  #   container_name: gio_apim_mongodb
  #   restart: always
  #   volumes:
  #     - data-mongo:/data/db
  #     - ./logs/apim-mongodb:/var/log/mongodb
  #   networks:
  #     - storage

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
    networks:
      - storage
    ports:
      - 8080:8080 