version: '3'
services:
  mariadb:
    image: bitnami/mariadb:latest
    volumes:
      - mariadb_data:/bitnami
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  wordpress:
    image: bitnami/wordpress:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - wordpress_data:/bitnami
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_USERNAME=admin
      - WORDPRESS_PASSWORD=admin
      - WORDPRESS_EMAIL=erick.pham@360f.com
      - WORDPRESS_FIRST_NAME=Erick
      - WORDPRESS_LAST_NAME=Pham
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local