version: '3'

services:
  mssql_server:
    container_name: mssql_server
    image: mcr.microsoft.com/mssql/server:2017-CU21-ubuntu-16.04
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=@Abc123456
      - MSSQL_PID=Enterprise
    ports:
      - "1433:1433"
    restart: always  
    volumes:
      - mssql_data:/var/opt/mssql
volumes:
  mssql_data:
    driver: local