version: '2'

services:
  mongodb-primary:
    image: 'bitnami/mongodb:4.0'
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    ports: 
      - '27017:27017' 
    volumes:
      - 'mongodb_master_data:/bitnami'
    networks:
      - b2c_backend  

  mongodb-secondary:
    build: ./
    image: 'bitnami/mongodb:4.0'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    networks:
      - b2c_backend    
  mongodb-arbiter:
    build: ./
    image: 'bitnami/mongodb:4.0'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    networks:
      - b2c_backend 
volumes:
  mongodb_master_data:
    driver: local
networks: 
  b2c_backend:    