version: '3'

services:
  crm_web:
    container_name: crm_web
    build: ./
    environment:
      - MYSQL_HOST=crm_db
      # - MYSQL_HOST=host.docker.internal
      - MYSQL_DB_NAME=crm
      - MYSQL_USER=root
      - MYSQL_PASSWORD=@Abc123456
      - MYSQL_PORT=3306
    ports:
      - "3300:80"
    # restart: always  
    networks: 
      - crm
    volumes:
      - D:/projects/docker-compose/suitecrm_metabase/crm/crm:/var/www/html/suitecrm
    #  - D:/projects/docker-compose/suitecrm_metabase/SuiteCRM-7.11.18:/var/www/html/suitecrm
    #  - crm_web_data:/var/www/html
  crm_db:
    container_name: crm_db
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=@Abc123456
      - MYSQL_USER=SuiteCRM
      - MYSQL_PASSWORD=@SuiteCRM
    ports:
      - "3308:3306"
    # restart: always  
    networks: 
      - crm
    volumes:
      - mysql_data:/var/lib/mysql
  crm_metabase:
    container_name: metabase
    image: metabase/metabase
    environment:
      - MB_DB_TYPE=mysql
      - MB_DB_DBNAME=crm_report
      - MB_DB_PORT=3306
      - MB_DB_USER=root
      - MB_DB_PASS=@Abc123456
      - MB_DB_HOST=crm_db
      - MB_JETTY_PORT=80
    ports:
      - "3301:80"
    restart: always  
    networks: 
      - crm
    # depends_on:
    #   - crm_db
volumes:
  mysql_data:
  crm_web_data:  
networks: 
  crm: