version: '3'

services:
  db:
    build: ./
    container_name: mysql
    environment:
     - MYSQL_ROOT_PASSWORD=Palomino1!
     - MYSQL_DATABASE=foresightpro
     - MYSQL_PASSWORD=foresightpro_dev
    volumes:
      - D:\\projects\\docker-compose\\volumes\\mysql_latest:/var/lib/mysql
    networks:
      - backend
    # restart: always
    ports:
      - 3306:3306

volumes:
  db-data:
networks: 
  backend:
