FROM redis:6.2-rc1
COPY redis.conf /usr/local/etc/redis/redis.conf
# CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
CMD ["redis-server", "--requirepass dM:hGz{F:JeJ5ck-DHsj]BUQxDJ-/T-J5CM&", "--save ''","--appendonly no"]