version: '3.7'
# services:
#   redis:
#     build: .
#     container_name: redis_ssl
#     ports:
#       - 6380:6380
services:
  # fix-redis-volume-ownership: # This service is to authorise redis-master with ownership permissions
  #   image: 'bitnami/redis:latest'
  #   user: root
  #   command: chown -R 1001:1001 /bitnami
  #   volumes:
  #     - ./data/redis:/bitnami
  #     - ./data/redis/conf/redis.conf:/opt/bitnami/redis/conf/redis.conf
  redis-master:
    image: 'bitnami/redis:latest'
    ports:
      - '6379:6380'
    environment:
      - REDIS_TLS_ENABLED=yes
      - REDIS_TLS_CERT_FILE=/opt/bitnami/redis/certs/redis.crt
      - REDIS_TLS_KEY_FILE=/opt/bitnami/redis/certs/redis.key
      - REDIS_TLS_CA_FILE=/opt/bitnami/redis/certs/redisCA.crt
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=my_master_password
    networks: 
      - redis  
    volumes:
      - ./data/redis-persistence:/bitnami

  redis-replica:
    image: 'bitnami/redis:latest'
    # ports:
    #   - '6379'
    depends_on:
      - redis-master
    networks: 
      - redis   
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=my_master_password
      - REDIS_PASSWORD=my_replica_password
      - REDIS_TLS_ENABLED=yes
      - REDIS_TLS_CERT_FILE=/opt/bitnami/redis/certs/redis.crt
      - REDIS_TLS_KEY_FILE=/opt/bitnami/redis/certs/redis.key
      - REDIS_TLS_CA_FILE=/opt/bitnami/redis/certs/redisCA.crt
networks: 
  redis:
# run docker-compose up --detach --scale redis-master=1 --scale redis-secondary=3